### ISSUE TITLE
SyntaxError: f-string expression part cannot include a backslash

### ISSUE THREAD

**Issue by wingerbijay** [iDigitalFlame/ThunderStorm#3]
Hi, I am getting this error when I am trying to install the latest version of ThunderStrom? It is something because I am doing something stupid and wrong? 

Thanks 

└─$ python3 bin/doppler -a "http://ip:port" -p supersecret
Traceback (most recent call last):
  File "/home/[user]/c2/ThunderStorm/bin/doppler", line 23, in <module>
    from include.cli.shell import Shell
  File "/home/[user]/c2/ThunderStorm/doppler/include/cli/shell.py", line 54, in <module>
    from include.cli.main import MenuMain
  File "/home/[user]/c2/ThunderStorm/doppler/include/cli/main.py", line 19, in <module>
    from include.cli.helpers import is_valid_name, make_menu, complete_with_all
  File "/home/user/c2/ThunderStorm/doppler/include/cli/helpers.py", line 519
    )
    ^
SyntaxError: f-string expression part cannot include a backslash

**Comment by iDigitalFlame** [comment]
Thanks for the submission, nah it's not from something you did stupid or anything.

Was there any input into the console after the `python3 bin/doppler -a "http://ip:port" -p supersecret` command? Or did it show that right as you executed it? _(Like any Doppler commands, or any `ls` commands in the main/bolts menu)_

I see the potential issue in `helpers.py:519` where I use `.replace(')\\Z', '')` in an f-string _(which I'm 99% sure it's it)_, but wanted to confirm as that shoudln't happen right after Doppler start.

Thanks!

**Comment by wingerbijay** [comment]
It did show right after the Doppler command. I did not get any shell/console to enter any command. 

Cheers

**Comment by iDigitalFlame** [comment]
Gotcha. I just pushed my fixes if you want to pull the latest and let me know if that works!

**Comment by wingerbijay** [comment]
hi I tried new fresh install on new vm but before reaching that point I am getting this. have you ever come across this?
thanks 

![image](https://github.com/user-attachments/assets/70525c75-6559-4784-9c01-ab391d257d0f)

**Comment by iDigitalFlame** [comment]
Oh yup, that's cause of a fix for go1.23. Check your `go version`. If it's older if you can update it (golang) that'd be great. If you can't, just edit the `build.sh` script and remove `-checklinkname=0` from the build line.

**Comment by iDigitalFlame** [comment]
If you want, I just pushed a commit for the `build.sh` script to detect the go version and change it's arguments. You can use that instead of updating. Thanks!

**Comment by wingerbijay** [comment]
Hi it works both ways. with older go version and the newer one as well. Thanks heaps
